allow:
  ip: '*.*.*.*'

server:
  port: '8080'

spring:
  datasource:
    url: jdbc:${API_DB_URL}
    username: ${API_DB_USER}
    password: ${API_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${API_AUTH_ISSUER_URI}
